name: Build SunamoClipboard

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoClipboard
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoClipboard/SunamoClipboard.csproj

    - name: Build
      run: dotnet build SunamoClipboard/SunamoClipboard.csproj --configuration Release --no-restore

  test:
    name: Test SunamoClipboard.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoClipboard.Tests/SunamoClipboard.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoClipboard.Tests/SunamoClipboard.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoClipboard.Tests/SunamoClipboard.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
